### ISSUE TITLE
Error in getting Token Price 

### ISSUE THREAD

**Issue by bergmedia3** [ethereum-boilerplate/ethereum-react-native-boilerplate#36]
I am trying to get the token price from useTokenPrice hook  but its giving me this error 
Error:
Fetch Price error {"code": 141, "error": "Invalid function: \"getTokenPrice\""}

**Comment by abdulmalik97** [comment]
Did you make sure to initialise Morlais by adding the server URL and app id in the .env file? 

Also, if you want more elaborate help, please head on to the forum link - 
https://forum.moralis.io/t/ethereum-react-native-boilerplate-questions/4511/107
