### ISSUE TITLE
Please elaborate on yarn android

### ISSUE THREAD

**Issue by mobilekosmos** [ethereum-boilerplate/ethereum-react-native-boilerplate#7]
I run yarn Android and I see a list of accoutns with 100Eth on the command prompt on Windows but then nothings happens. Don't know how to run this on a connected device. I do have a complete Android dev environment setup.

**Comment by ivan-liljeqvist** [comment]
https://forum.moralis.io/t/ethereum-react-native-boilerplate-questions/4511 for help please post here
