### ISSUE TITLE
loader handler failed for UI kitten

### ISSUE THREAD

**Issue by Sheshiyer** [ethereum-boilerplate/ethereum-react-native-boilerplate#8]
Web Bundling complete 19183ms
./node_modules/@ui-kitten/components/ui/input/input.component.js 105:38
Module parse failed: Unexpected token (105:38)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         this.webEventResponder = devsupport_1.WebEventResponder.create(this);
|         this.focus = () => {
>             this.textInputRef.current?.focus();
|         };
|         this.blur = () => {
./node_modules/@ui-kitten/components/ui/tab/tabBar.component.js 137:37
Module parse failed: Unexpected token (137:37)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     }
|     scrollToIndex(params) {
>         this.tabIndicatorRef.current?.scrollToIndex(params);
|     }
|     scrollToOffset(params) {
./node_modules/@ui-kitten/components/ui/popover/popover.component.js 148:38
Module parse failed: Unexpected token (148:38)

is there any workaround to fix this ?

**Comment by ivan-liljeqvist** [comment]
https://forum.moralis.io/t/ethereum-react-native-boilerplate-questions/4511 for help please post here
